spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/crm
    username: postgres
    password: 1234asdf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
